import { createApp } from 'vue'
import App from './App.vue'
import'bootstrap'
import 'bootstrap/dist/js/bootstrap.min.js'
import'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/js/bootstrap.bundle.min.js'
import './plantilla/css/vendor.css'
import './plantilla/style.css'
import router from './router'
import axios from 'axios'   
axios.defaults.baseURL = 'http://localhost:8000/api/'
createApp(App).use(router).mount('#app')
